name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '*/5 * * * *'   #

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
            npm init -y
            npm install newman newman-reporter-htmlextra
        
      - name: Run Tests and Generate HTML Report
        env:
            POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        run: |
            npx newman run "https://api.postman.com/collections/52498897-2a596169-603f-43d2-b980-f74c235385b6?access_key=$POSTMAN_API_KEY" \
            -e EnvTestEmployee.postman_environment.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export newman-report.html

          # node ./report.js ##Remove to run the command

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4   # ✅ updated এখানে
        with:
          name: newman-html-report
          path: newman-report.html

      - name: Send Email on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_EMAIL }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ❌ API Test Failed
          body: |
            Your API test has FAILED ❌
            Repo: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Check details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.SMTP_EMAIL }}
          attachments: newman-report.html
      - name: Send Email on Success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_EMAIL }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ✅ API Test Passed
          body: |
            Your API test has PASSED ✅
            Repo: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            View run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.SMTP_EMAIL }}
          attachments: newman-report.html
